version: 2
jobs:
  build_and_push:
    docker:
      - image: docker:stable
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Create version.json
          command: |
            # create a version.json per https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
            printf '{"commit":"%s","version":"%s","source":"https://github.com/%s/%s","build":"%s"}\n' \
            "$CIRCLE_SHA1" \
            "$CIRCLE_TAG" \
            "$CIRCLE_PROJECT_USERNAME" \
            "$CIRCLE_PROJECT_REPONAME" \
            "$CIRCLE_BUILD_URL" > version.json

      - run:
          name: Build Docker image
          command: |
            docker info
            docker build -t ${CIRCLE_PROJECT_REPONAME}:build .

      - run:
          name: Push to Dockerhub
          command: |
            echo "${DOCKER_PASSWORD}" | docker login -u="${DOCKER_USERNAME}" --password-stdin
            export DOCKER_IMAGE="mozilla/${CIRCLE_PROJECT_REPONAME}:latest"
            if [ -n "${CIRCLE_TAG}" ]; then
                export DOCKER_IMAGE="mozilla/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_TAG}"
            fi

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker tag "${CIRCLE_PROJECT_REPONAME}:build" "${DOCKER_IMAGE}"
                docker push "${DOCKER_IMAGE}"
            fi

workflows:
  version: 2

  # workflow jobs are _not_ run in tag builds by default
  # we use filters to whitelist jobs that should be run for tags

  # workflow jobs are run in _all_ branch builds by default
  # we use filters to blacklist jobs that shouldn't be run for a branch

  # see: https://circleci.com/docs/2.0/workflows/#git-tag-job-execution

  build_and_push:
    jobs:
      - build_and_push:
          filters:
            tags:
              only: /.*/
