# Generated by Django 2.0.4 on 2018-05-11 17:32

import bec_alerts.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('bec_alerts', '0001_initial'), ('bec_alerts', '0002_issuebucket'), ('bec_alerts', '0003_auto_20180426_1213'), ('bec_alerts', '0004_auto_20180426_1853'), ('bec_alerts', '0005_auto_20180501_1644'), ('bec_alerts', '0006_issue_message'), ('bec_alerts', '0007_issue_groupid')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            'CREATE EXTENSION IF NOT EXISTS hll'
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=255, unique=True)),
                ('last_seen', models.DateTimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TriggerRun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField()),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IssueBucket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_set', bec_alerts.models.HyperLogLogField()),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bec_alerts.Issue')),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='issuebucket',
            unique_together={('issue', 'date')},
        ),
        migrations.AddField(
            model_name='issue',
            name='module',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='stack_frames',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
        migrations.CreateModel(
            name='UserIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notified', models.DateTimeField(default=None, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bec_alerts.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bec_alerts.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='issues',
            field=models.ManyToManyField(through='bec_alerts.UserIssue', to='bec_alerts.Issue'),
        ),
        migrations.AlterUniqueTogether(
            name='userissue',
            unique_together={('user', 'issue')},
        ),
        migrations.AddField(
            model_name='issue',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='groupId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
