# Generated by Django 2.0.4 on 2018-04-26 23:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bec_alerts', '0003_auto_20180426_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='module',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='issue',
            name='stack_frames',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
