# Generated by Django 2.0.4 on 2018-05-01 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bec_alerts', '0004_auto_20180426_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_notified', models.DateTimeField(default=None, null=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bec_alerts.Issue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bec_alerts.User')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='issues',
            field=models.ManyToManyField(through='bec_alerts.UserIssue', to='bec_alerts.Issue'),
        ),
        migrations.AlterUniqueTogether(
            name='userissue',
            unique_together={('user', 'issue')},
        ),
    ]
