# Generated by Django 2.0.4 on 2018-05-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bec_alerts', '0005_auto_20180501_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='message',
            field=models.CharField(default='', max_length=255),
        ),
    ]
