# Generated by Django 2.0.4 on 2018-05-07 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bec_alerts', '0006_issue_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='groupId',
            field=models.CharField(default='', max_length=255),
        ),
    ]
